### ISSUE TITLE
First 3bot pages

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/3bot#10]
The first page a 3bot will show after deployment is the initialization page.

The page URL will be sent by email to the user. The URL will contain a token that needs to be passed in the URL in order for the 3bot to know he's talking to the proper use.
Withouth this token the 3bot should only show a read-only page explaining why it cannot continue without proper token.

If the token is valid, a form/chat flow should start:
- Do you already have a seed
- Want to generate a new seed
- ...

Once this step is pass, the rest of the configuration of the 3bot can continue.

**Comment by jdelrue** [comment]
https://github.com/threefoldfoundation/3bot/blob/master/specs/initialize.md

**Comment by rkhamis** [comment]
@zaibon I already created issues #6 and #7 for some initial chatflows that we'll need.

I think here we should have a discussion about what exactly will be required for the 3bot to be initialized. But we can start work on the initial spec described in #6

**Comment by zaibon** [comment]
duplicate of #6
