### ISSUE TITLE
CoreDNS plugin to read 3bot double name from TFChain

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/3bot#12]

**Comment by xmonader** [comment]
I've semi working plugin now but still needs 

1- configurable explorer endpoint
2- restrict format on the returned addresses in whois response from explorer to include only ip4/ip6 only of the locations

**Comment by xmonader** [comment]
plugin exists here https://github.com/threefoldtech/threebot_coredns

**Comment by zaibon** [comment]
obsolete
