### ISSUE TITLE
Design updated images for sections of 3Bot wiki

### ISSUE THREAD

**Issue by juradoo** [threefoldfoundation/3bot#27]
Updated images needed for 3Bot wiki sections: 

- [x] 3Bot Wiki Intro

- [x] What Is 3Bot

- [x] How to get your 3Bot

**Comment by Zizaster** [comment]
@juradoo three images delivered.. please send the required information needed to complete the remaining tasks.

**Comment by juradoo** [comment]
Thank you @Zizaster - 3 images loaded here: https://github.com/threefoldfoundation/3bot/tree/master/docs/img
and updated in .md files. 

https://github.com/threefoldfoundation/3bot/blob/master/docs/img/3bot_wiki_home.png
https://github.com/threefoldfoundation/3bot/blob/master/docs/img/3bot_own_digital_life.png
https://github.com/threefoldfoundation/3bot/blob/master/docs/img/3bot_your_digital_self.png
