### ISSUE TITLE
Spec API between front end and bootstrap bot

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/3bot#9]
Some high level API has already been defined in https://github.com/threefoldfoundation/3bot/blob/master/specs/androidapp.md

But we should continue this work and make sure a proper interface is define for the 3bot gedis actor.

Protocol is also to be decided: @jdelrue I guess this one is for you. What is easier for you to use from the app.

**Comment by jdelrue** [comment]
Will test next week!
